server:
  port: 9091
spring:
  application:
    name: Employee_MGMT_Service
##mysql database configuration
  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/world
      username: root
      password: root
##oracle database configuration
  oracle:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
      password: admin
##hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true