server:
  port: 8324
spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: Product-Service
          uri: lb://Product-Service
          predicates:
            - path= /api/product
        - id: Order-Service
          uri: lb://Order-Service
          predicates:
            - path= /api/order
        - id: Inventory-Service
          uri: lb://Inventory-Service
          predicates:
            - path= /api/inventory
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level: 
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinationLocator: INFO