server:
  port: 9491
spring:
  application:
    name: Merchant-Service
  datasource:
    url: jdbc:mysql://localhost:3306/merchant
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true