server:
  port: 8323
spring:
  application:
    name: Inventory-Service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
        