server:
  port: 8823
spring:
  application:
    name: AssociationMapping
  datasource:
    url: jdbc:mysql://localhost:3306/association
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true